# generate_data/Dockerfile
FROM python:3.11-slim

WORKDIR /app

# Copier requirements.txt et installer les dépendances
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copier le code FastAPI
COPY . .

# Lancer streamlit
CMD ["streamlit", "run", "frontend/app.py", "--server.port=8501"]
# CMD ["python", "-m", "streamlit", "run", "frontend/app.py", "--server.port=8501"]
