services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: job_matching_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: job_matching
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./airflow/init.sql:/docker-entrypoint-initdb.d/01_init_airflow.sql # CREATE USER airflow / CREATE DATABASE airflow
      - ./database/init.sql:/docker-entrypoint-initdb.d/02_init_project.sql
      # - ./database/init.sql:/docker-entrypoint-initdb.d/02_init_project.sql  # ligne pour charger automatiquement votre script
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: job_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres

  minio:
    image: minio/minio
    container_name: job_minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
  
  create-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 10;
      /usr/bin/mc alias set myminio http://minio:9000 ${MINIO_USER} ${MINIO_PASSWORD};
      /usr/bin/mc mb myminio/bronze;
      /usr/bin/mc mb myminio/silver;
      /usr/bin/mc mb myminio/gold;
      "
  
  airflow-webserver:
    build:
      context: .
    image: apache/airflow:2.8.0
    container_name: job_airflow-webserver
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - _AIRFLOW_DB_UPGRADE=true        # initialise la BDD automatiquement
      - _AIRFLOW_WWW_USER_CREATE=true   # crée l'admin automatiquement
      - _AIRFLOW_WWW_USER_USERNAME=admin
      - _AIRFLOW_WWW_USER_PASSWORD=admin
      - AIRFLOW_VAR_CLIENT_ID=${CLIENT_ID}
      - AIRFLOW_VAR_CLIENT_SECRET=${CLIENT_SECRET}
      - MINIO_HOST=job_minio:9000 
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command: webserver
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
  
  airflow-scheduler:
    image: apache/airflow:2.8.0
    container_name: job_airflow-scheduler
    environment:
      - AIRFLOW__CORE__EXECUTOR=LocalExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://airflow:airflow@postgres/airflow
      - AIRFLOW__LOGGING__LOGGING_LEVEL=INFO
      - MINIO_HOST=job_minio:9000
      - MINIO_USER=${MINIO_USER}
      - MINIO_PASSWORD=${MINIO_PASSWORD}
    depends_on:
      - postgres
      - airflow-webserver
    command: scheduler
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      
  fastapi:
    build:
      context: ./backend  # dossier contenant ton api.py et requirements.txt
      dockerfile: Dockerfile
    container_name: job_fastapi
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  streamlit:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: job_streamlit
    ports:
      - "8501:8501"
    volumes:
      - ./frontend:/app
    environment:
      - STREAMLIT_SERVER_FILE_WATCHER_TYPE=poll
      - PYTHONPATH=/app
    # command: streamlit run frontend/app.py --server.port=8501 --server.fileWatcherType=poll
    command: streamlit run app.py --server.port=8501 --server.fileWatcherType=poll
    depends_on:
      - fastapi

volumes:
  postgres_data:
  minio_data: